/**
 * MULTIGRAPH
 *
 * Project for Mattia Zago Master Thesis
 *
 * (C) 2015 - Mattia Zago
 *
 */
package es.um.multigraph.decision.poolsappasitmoop;

import es.um.multigraph.decision.basegraph.*;
import java.awt.Color;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author Mattia Zago <a href="mailto:dev@zagomattia.it">dev@zagomattia.it</a>
 */
public class BayesianJDialogCMEdge extends javax.swing.JDialog {
    BayesianAttackGraphAdapted model;
    /**
     * Creates new form NewJDialog
     */
    public BayesianJDialogCMEdge(BayesianModelConfiguration parent, boolean modal, BayesianAttackGraphAdapted model) {
        super(parent, modal);
        this.model = model;
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setModal(modal);
    }

    public BayesianNode from;
    public BayesianNode to;
    public Double pr = 1d;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        TO_List = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_SAVE = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        FROM_List = new javax.swing.JList();
        BTN_CANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new Edge");

        TO_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TO_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TO_ListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(TO_List);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("From CM Node");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("To Node");

        BTN_SAVE.setText("SAVE");
        BTN_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SAVEActionPerformed(evt);
            }
        });

        FROM_List.setModel(new ListModelNodes(this.model.getCMNodes()));
        FROM_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        FROM_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FROM_ListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(FROM_List);

        BTN_CANCEL.setText("CANCEL");
        BTN_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_CANCEL)
                    .addComponent(BTN_SAVE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TO_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TO_ListValueChanged
        this.to = (BayesianNode) TO_List.getSelectedValue();
        if(to != null && from != null)
            if(!from.canReach(to))
                this.TO_List.setBackground(ok);
    }//GEN-LAST:event_TO_ListValueChanged

    private void BTN_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SAVEActionPerformed
        if(this.to == null) {
            JOptionPane.showMessageDialog(rootPane, "You need to choose a destination node", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }   
        if(this.from == null) {
            JOptionPane.showMessageDialog(rootPane, "You need to choose a source node", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        dispose();
    }//GEN-LAST:event_BTN_SAVEActionPerformed

    private void FROM_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FROM_ListValueChanged
        this.from = (BayesianNode) FROM_List.getSelectedValue();
        if(this.from != null) {
            Collection<? extends Node> nlist = ((BayesianAttackGraphAdapted)model).getNodesNotCM();
            nlist.removeIf(n -> n.canReach(from)); // remove all reachable nodes
            from.getOut().stream().forEach(e -> nlist.remove(e.getTo()));
            TO_List.setModel(new ListModelNodes(nlist));
            TO_List.clearSelection();
            TO_List.setBackground(clear);
            
            if(nlist.isEmpty())
                TO_List.setBackground(wrong);
        }
        this.repaint();
    }//GEN-LAST:event_FROM_ListValueChanged

    private void BTN_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CANCELActionPerformed
        this.from = null;
        this.to = null;
        dispose();
    }//GEN-LAST:event_BTN_CANCELActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CANCEL;
    private javax.swing.JButton BTN_SAVE;
    private javax.swing.JList FROM_List;
    private javax.swing.JList TO_List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private static final Color wrong = new Color(255, 153, 153);
    private static final Color ok = new Color(153, 255, 153);
    private static final Color clear = new Color(240, 240, 240);
}
