/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.um.multigraph.decision.almohri.Main;
import Graph.GraphReader;
import Success.InitialSolution;
import Graph.*;
//import Success.*;
import es.um.multigraph.decision.almohri.Success.SLP;
/**
 *
 * @author almohri
 */
public class Main {
    public static void main(String[] args){
        GraphReader reader = new GraphReader();
        Graph g;
        String path = "";
        try {
            path = args[0];
        }
        catch(Exception e) {
           System.out.println("Please enter the path to attack graph source files (generated by MulVAL).");  
        }
        g = reader.readGraph(path, true);
        System.out.println("Read a total of "+g.vertices.size()+" vertices.");
        System.out.println("Read a total of "+g.totalFactNodes()+" fact vertices.");
        
        
        InitialSolution init = new InitialSolution();
        init.findInitialSolution(g,path);
        
        SLP slp = new SLP();
        slp.solve(path, g);
    }
}
